services:
  mysql:
    image: mysql:8.0
    container_name: mysql_patients
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: medilabo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - medilabo-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_notes
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - medilabo-network

  patient-service:
    build: ./PatientService
    container_name: patient-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/medilabo
      - SPRING_DATASOURCE_USERNAME=${MYSQL_ROOT_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    depends_on:
      - mysql
    networks:
      - medilabo-network

  note-service:
    build: ./NoteService
    container_name: note-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - medilabo-network

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_SECURITY_USER_NAME=${API_USERNAME}
      - SPRING_SECURITY_USER_PASSWORD=${API_PASSWORD}
    depends_on:
      - patient-service
      - note-service
    networks:
      - medilabo-network

  frontend:
    build: ./Front-end
    container_name: frontend
    ports:
      - "8082:8082"
    environment:
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - GATEWAY_URL=http://gateway:8080
    depends_on:
      - gateway
    networks:
      - medilabo-network

  risk-assessment-service:
    build: ./RiskAssessmentService
    container_name: risk-assessment-service
    ports:
      - "8084:8084"
    environment:
      - NOTE_SERVICE_URL=http://note-service:8083
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    depends_on:
      - note-service
      - patient-service
    networks:
      - medilabo-network

volumes:
  mysql_data:
  mongodb_data:

networks:
  medilabo-network:
    driver: bridge
