server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: patient_service
            uri: http://localhost:8081
            predicates:
              - Path=/api/patients/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# CORS Configuration
spring.mvc.cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE
  allowed-headers: "*"
  allow-credentials: true
